#!/usr/bin/python3
#
# Convert Yamaha DX7 firmware v1.8 assembler
# into comments inside a C++ header

with open("yamaha_dx7_rom_v1.8.asm") as asm_file:
   with open("yamaha_dx7_rom_v1.8.h", "w") as cpp_file:

      for line in asm_file:
         if line == "\n":
            cpp_file.write("//\n")
         else:
            cpp_file.write(f"// {line}")
