#!/usr/bin/python3
#
# Extract Yamaha DX7 firmware v1.8 assembler from the 
# comments in the C++ header "DX7_v1_8.h"

with open("DX7_v1_8.h") as cpp_file:
   with open("DX7_v1_8.asm", "w") as asm_file:

      for line in cpp_file:

         if line[0:3] == "///":
            pass

         elif line[0:3] == "// ":
            asm_file.write(line[3:])

         elif line[0:2] == "//":
            asm_file.write('\n')
